kumuluzee:
  name: artist-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8084
    http:
      port: 8084
  discovery:
    etcd:
      hosts: http://localhost:2379
  datasources:
    - jndi-name: jdbc/ArtistsDS
      connection-url: jdbc:postgresql://localhost:5434/artist
      username: postgres
      password: postgres
      max-pool-size: 20
  health:
     # servlet:
     #   mapping: /health
     #   enabled: true
      checks:
        data-source-health-check:
          jndi-name: jdbc/ArtistsDS
  metrics:
      web-instrumentation:
        - name: metricsEndpoint
          url-pattern: /metrics/*
        - name: artistsEndpoint
          url-pattern: /v1/artists/*