kumuluzee:
  name: artist-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8084
    http:
      port: 8084
#  discovery:
#    etcd:
#      hosts: http://192.168.99.100:2379
  datasources:
    - jndi-name: jdbc/ArtistsDS
      connection-url: jdbc:postgresql://localhost:5434/artist
      username: postgres
      password: postgres
      max-pool-size: 20